services:
  app:
    build: .
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"

  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"        # Port exposé sur la machine hôte : 8000
    environment:
      - PORT=8000          # Définition claire de la variable d'environnement
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/html
    depends_on:
      - app              # Syntaxe simplifiée pour depends_on

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - target: 5432
        published: 5434
        protocol: tcp
        mode: host
